data:
  class_path: ddpm_playground.data.GlobDatasetForGM
  init_args:
    root_path: data/ct_data
    pattern: "*.jpg"
    recursive: True
    repeat: 16
    image_size: 64
    batch_size: 192
    num_workers: 16

model:
  class_path: ddpm_playground.models.GaussianDiffusion
  init_args:
    model:
      class_path: ddpm_playground.models.UNet
      init_args:
        in_channels: 1
        num_channels: 64
        channel_multiplier: [1, 2, 4, 8]
    image_size: 64
    timesteps: 1000
    sampling_timesteps: 250
    loss_type: l1
    objective: pred_noise
    beta_schedule: cosine
    p2_loss_weight_gamma: 0.
    p2_loss_weight_k: 1.
    ddim_sampling_eta: 1.
    learning_rate: 0.00001

trainer:
  max_epochs: 200
  accelerator: "gpu"
  precision: 16
  devices: 2
  strategy: ddp

  logger:
    - class_path: ddpm_playground.utils.logger.WandbLogger
      init_args:
        project: ddpm-playground
        entity: viv
        name: Debug
        notes: "Debug"
        tags: ["Debug"]
        save_code: True

  callbacks:
    - class_path: RichProgressBar
      init_args:
        leave: True
    - class_path: ModelCheckpoint
      init_args:
        filename: "epoch_{epoch:03d}"
        auto_insert_metric_name: False
        save_top_k: -1
        every_n_epochs: 1
    - LearningRateMonitor

  default_root_dir: wandb

seed_everything: 23333
